# Generated by Django 4.1.7 on 2023-07-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='province',
        ),
    ]
